!$THEME = "drew"

!$BLACK  = "#000121"
!$WHITE  = "#FFFFFF"
!$BLUE = "blue"
!$YELLOW = "yellow"

!$BGCOLOR = $WHITE
!$FGCOLOR = $BLACK

'!ifndef $FONT_NAME
'  !$FONT_NAME = "Segoe UI"
'!endif
!$FONT_NAME = "Segoe UI"

!ifndef $FONT_NAME_MONOSPACED
  !$FONT_NAME_MONOSPACED = "Courier"
!endif

<style>
  root {
    BackgroundColor $BGCOLOR
    FontColor $FGCOLOR
    FontName $FONT_NAME
    HyperLinkColor $YELLOW
    LineColor $FGCOLOR
    LineThickness 1
    Margin 3
    Padding 3
  }
  document {
    caption {
      FontSize 10
      LineThickness 0
    }
    footer {
      FontSize 10
      LineThickness 0
      Margin 0
    }
    header {
      FontSize 10
      LineThickness 0
    }
    title {
      FontSize 16
      LineThickness 0
    }
  }
  groupHeader {
    BackgroundColor $FGCOLOR
    FontColor $BGCOLOR
    FontStyle normal
  }
  node {
    MaximumWidth 300
  }
  referenceHeader {
    BackgroundColor $FGCOLOR
    FontColor $BGCOLOR
    FontStyle normal
  }
  separator {
    BackgroundColor $FGCOLOR
    FontColor $BGCOLOR
    FontStyle normal
  }
</style>

skinparam ArrowLollipopColor $FGCOLOR
skinparam BackgroundColor $BGCOLOR
skinparam DefaultFontName $FONT_NAME
skinparam DefaultMonospacedFontName $FONT_NAME_MONOSPACED
skinparam LifelineStrategy nosolid
skinparam ParticipantPadding 5
skinparam SequenceLifeLineBorderColor $FGCOLOR
skinparam Shadowing false
skinparam UseBetaStyle true
'skinparam SequenceParticipant
skinparam SequenceParticipantBorderThickness 1
skinparam SequenceReferenceHeaderBackgroundColor $BGCOLOR
skinparam SequenceNewpageSeparatorColor red
skinparam SequenceMessageAlignment right
skinparam SequenceMessageTextAlignment right
skinparam SequenceActorBorderThickness 1
skinparam SequenceArrowThickness 1

skinparam Boundary {
  FontColor $FGCOLOR
}
skinparam Box {
  Padding 5
}
skinparam Footer {
  FontColor $FGCOLOR
  FontName $FONT_NAME
}
skinparam Header {
  FontColor $FGCOLOR
  FontName $FONT_NAME
}
skinparam Hyperlink {
  Color $YELLOW
}
skinparam IconPackage {
  Color $FGCOLOR
  BackgroundColor $BGCOLOR
}
skinparam IconPrivate {
  Color $FGCOLOR
  BackgroundColor $BGCOLOR
}
skinparam IconProtected {
  Color $FGCOLOR
  BackgroundColor $BGCOLOR
}
skinparam IconPublic {
  Color $FGCOLOR
  BackgroundColor $BGCOLOR
}
skinparam Note {
  FontColor $FGCOLOR
  FontName $FONT_NAME
}
skinparam Object {
  BorderColor $FGCOLOR
}

skinparam Package {
  BorderColor $FGCOLOR
  FontColor $FGCOLOR
  FontName $FONT_NAME
}

skinparam State {
  BackgroundColor $BGCOLOR
  BorderColor $FGCOLOR
}

'''''''''''
skinparam SequenceDelay {
  BorderThickness 1
  BorderColor red
  BackgroundColor $BGCOLOR
  Alignment right

  FontColor $FGCOLOR
  FontName $FONT_NAME
  FontSize 10
  FontStyle normal
}

skinparam SequenceBox {
  BorderThickness 1
  BorderColor $BLUE
  BackgroundColor $BGCOLOR
  Alignment right

  FontColor $FGCOLOR
  FontName $FONT_NAME
  FontSize 10
  FontStyle normal
}

skinparam SequenceLifeLine  {
  BorderThickness 1
  BorderColor $BLUE
  BackgroundColor $BGCOLOR
  Alignment right

  FontColor $FGCOLOR
  FontName $FONT_NAME
  FontSize 10
  FontStyle normal
}

skinparam SequenceGroupHeader {
  BorderThickness 1
  BorderColor red
  BackgroundColor $BGCOLOR
  Alignment right

  FontColor $FGCOLOR
  FontName $FONT_NAME
  FontSize 10
  FontStyle normal
}

skinparam SequenceDelay {
  BorderThickness 1
  BorderColor red
  BackgroundColor $BGCOLOR
  Alignment right

  FontColor $FGCOLOR
  FontName $FONT_NAME
  FontSize 10
  FontStyle normal
}

skinparam SequenceDivider {
  BorderThickness 1
  BorderColor red
  BackgroundColor $BGCOLOR
  Alignment right

  FontColor $FGCOLOR
  FontName $FONT_NAME
  FontSize 10
  FontStyle normal
}

skinparam SequenceReference {

  BorderThickness 1
  BorderColor red
  BackgroundColor $BGCOLOR
  Alignment right

  FontColor $FGCOLOR
  FontName $FONT_NAME
  FontSize 10
  FontStyle normal
}

skinparam SequenceStereotype {
  BorderThickness 1
  BorderColor red
  BackgroundColor $BGCOLOR
  Alignment right

  FontColor $FGCOLOR
  FontName $FONT_NAME
  FontSize 10
  FontStyle normal
}

skinparam SequenceTitle {
  BorderThickness 1
  BorderColor red
  BackgroundColor $BGCOLOR
  Alignment right

  FontColor $FGCOLOR
  FontName $FONT_NAME
  FontSize 10
  FontStyle normal
}
